import type { QuoteRead } from '@/api/client'

export function makeQuote(partial: Partial<QuoteRead> & Pick<QuoteRead, 'id'>): QuoteRead {
  return {
    cnpj: '11222333000181',
    client_name: 'Cliente',
    tiflux_client_id: 1,
    vhsys_client_id: null,
    status: 'draft',
    lead_temperature: 'quente',
    billed_by_type: null,
    billed_by_name: null,
    active_quote_version_id: null,
    current_version_number: null,
    implant_payment_plan: null,
    implant_discount_pct: null,
    implant_discount_value: null,
    implant_labor_hours: null,
    implant_labor_hourly_rate: null,
    monthly_payment_plan: null,
    monthly_discount_pct: null,
    monthly_discount_value: null,
    monthly_labor_hours: null,
    monthly_labor_hourly_rate: null,
    analyst_hourly_cost: null,
    implementation_hours: null,
    modules: [],
    client_email: null,
    contact_name: null,
    contact_email: null,
    contact_phone: null,
    extra_recipients: [],
    monthly_draft_json: null,
    notes: null,
    internal_notes: null,
    title: null,
    tiflux_ticket_number: null,
    ticket_link_status: null,
    ticket_link_catalog: null,
    ticket_link_checked_at: null,
    ticket_link_snapshot: null,
    vhsys_os_id: null,
    pdf_path: null,
    created_by: 1,
    created_at: '2026-09-18T12:00:00+00:00',
    updated_at: '2026-09-18T12:00:00+00:00',
    submitted_at: null,
    sent_at: null,
    approved_at: null,
    items: [
      {
        id: 1,
        quote_id: partial.id,
        section: 'implantacao',
        name: 'X',
        qty: 1,
        unit_value: 100,
        total_value: 100,
        template_key: null,
        sort_order: 0,
      },
    ],
    ...partial,
  }
}
